### ISSUE TITLE
Not able to move assigned axis to game's keybinds

### ISSUE THREAD

**Issue by matheyka** [Lasse-B/Sx2vJoy-test#11]
Hi!

I downloaded `vJoy`, set up my 3Dmouse as a joystick, like the instructions, started `Sx2vJoy.exe`, tabbed into Farming Simulator 22 and `CTRL+ALT+S`.

Then I move an axes and let go. `Sx2vJoy` recognizes this and starts the countdown. In FS22 i click to assign a key but when `Sx2vJoy` is done the assignment didn't work. It's like FS22 didn't receive and input.

Did I do something wrong or does this not work with Farming Simulator?

**Comment by 705Marc** [comment]
it works with the right settings xD

**Comment by matheyka** [comment]
I am an idiot.

**Comment by 705Marc** [comment]
no ls22 is difficult to setup :D
